# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import litserve_pb2 as litserve__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in litserve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/lightserver.Inference/Predict',
                request_serializer=litserve__pb2.PredictRequest.SerializeToString,
                response_deserializer=litserve__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.StreamPredict = channel.unary_stream(
                '/lightserver.Inference/StreamPredict',
                request_serializer=litserve__pb2.PredictRequest.SerializeToString,
                response_deserializer=litserve__pb2.PredictResponse.FromString,
                _registered_method=True)


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=litserve__pb2.PredictRequest.FromString,
                    response_serializer=litserve__pb2.PredictResponse.SerializeToString,
            ),
            'StreamPredict': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=litserve__pb2.PredictRequest.FromString,
                    response_serializer=litserve__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightserver.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lightserver.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightserver.Inference/Predict',
            litserve__pb2.PredictRequest.SerializeToString,
            litserve__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lightserver.Inference/StreamPredict',
            litserve__pb2.PredictRequest.SerializeToString,
            litserve__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModelReady = channel.unary_unary(
                '/lightserver.ModelControl/ModelReady',
                request_serializer=litserve__pb2.ModelReadyRequest.SerializeToString,
                response_deserializer=litserve__pb2.ModelReadyResponse.FromString,
                _registered_method=True)
        self.RepositoryIndex = channel.unary_unary(
                '/lightserver.ModelControl/RepositoryIndex',
                request_serializer=litserve__pb2.Empty.SerializeToString,
                response_deserializer=litserve__pb2.RepositoryIndexResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/lightserver.ModelControl/LoadModel',
                request_serializer=litserve__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=litserve__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/lightserver.ModelControl/UnloadModel',
                request_serializer=litserve__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=litserve__pb2.StatusResponse.FromString,
                _registered_method=True)


class ModelControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ModelReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RepositoryIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ModelReady': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelReady,
                    request_deserializer=litserve__pb2.ModelReadyRequest.FromString,
                    response_serializer=litserve__pb2.ModelReadyResponse.SerializeToString,
            ),
            'RepositoryIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.RepositoryIndex,
                    request_deserializer=litserve__pb2.Empty.FromString,
                    response_serializer=litserve__pb2.RepositoryIndexResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=litserve__pb2.LoadModelRequest.FromString,
                    response_serializer=litserve__pb2.StatusResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=litserve__pb2.UnloadModelRequest.FromString,
                    response_serializer=litserve__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightserver.ModelControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lightserver.ModelControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ModelReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightserver.ModelControl/ModelReady',
            litserve__pb2.ModelReadyRequest.SerializeToString,
            litserve__pb2.ModelReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RepositoryIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightserver.ModelControl/RepositoryIndex',
            litserve__pb2.Empty.SerializeToString,
            litserve__pb2.RepositoryIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightserver.ModelControl/LoadModel',
            litserve__pb2.LoadModelRequest.SerializeToString,
            litserve__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightserver.ModelControl/UnloadModel',
            litserve__pb2.UnloadModelRequest.SerializeToString,
            litserve__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
