# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: litserve.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'litserve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elitserve.proto\x12\x0blightserver\"\xa3\x01\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12;\n\x08metadata\x18\x03 \x03(\x0b\x32).lightserver.PredictRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x0fPredictResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\'\n\x11ModelReadyRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"#\n\x12ModelReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"&\n\x10LoadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"(\n\x12UnloadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"9\n\tModelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"A\n\x17RepositoryIndexResponse\x12&\n\x06models\x18\x01 \x03(\x0b\x32\x16.lightserver.ModelInfo2\x9f\x01\n\tInference\x12\x44\n\x07Predict\x12\x1b.lightserver.PredictRequest\x1a\x1c.lightserver.PredictResponse\x12L\n\rStreamPredict\x12\x1b.lightserver.PredictRequest\x1a\x1c.lightserver.PredictResponse0\x01\x32\xc0\x02\n\x0cModelControl\x12M\n\nModelReady\x12\x1e.lightserver.ModelReadyRequest\x1a\x1f.lightserver.ModelReadyResponse\x12K\n\x0fRepositoryIndex\x12\x12.lightserver.Empty\x1a$.lightserver.RepositoryIndexResponse\x12G\n\tLoadModel\x12\x1d.lightserver.LoadModelRequest\x1a\x1b.lightserver.StatusResponse\x12K\n\x0bUnloadModel\x12\x1f.lightserver.UnloadModelRequest\x1a\x1b.lightserver.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'litserve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=195
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_start=148
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_end=195
  _globals['_PREDICTRESPONSE']._serialized_start=197
  _globals['_PREDICTRESPONSE']._serialized_end=231
  _globals['_MODELREADYREQUEST']._serialized_start=233
  _globals['_MODELREADYREQUEST']._serialized_end=272
  _globals['_MODELREADYRESPONSE']._serialized_start=274
  _globals['_MODELREADYRESPONSE']._serialized_end=309
  _globals['_LOADMODELREQUEST']._serialized_start=311
  _globals['_LOADMODELREQUEST']._serialized_end=349
  _globals['_UNLOADMODELREQUEST']._serialized_start=351
  _globals['_UNLOADMODELREQUEST']._serialized_end=391
  _globals['_STATUSRESPONSE']._serialized_start=393
  _globals['_STATUSRESPONSE']._serialized_end=443
  _globals['_EMPTY']._serialized_start=445
  _globals['_EMPTY']._serialized_end=452
  _globals['_MODELINFO']._serialized_start=454
  _globals['_MODELINFO']._serialized_end=511
  _globals['_REPOSITORYINDEXRESPONSE']._serialized_start=513
  _globals['_REPOSITORYINDEXRESPONSE']._serialized_end=578
  _globals['_INFERENCE']._serialized_start=581
  _globals['_INFERENCE']._serialized_end=740
  _globals['_MODELCONTROL']._serialized_start=743
  _globals['_MODELCONTROL']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
