ensemble:
  steps:
    - name: square
      model: test_model
      version: "1"
      inputs:
        input: "$request.value"

    - name: cube
      model: test_model
      version: "2"
      inputs:
        input: "$square.output"
